### ISSUE TITLE
[BUG] Unable to discover port 70

### ISSUE THREAD

**Issue by YGHS4** [zcyberseclab/zscan#10]
### Current Behavior
Zscan result does not include port 70. In fact, port 70 is open and there is a vulnerability.

### Expected Behavior
Zscan can detect port 70.

### Steps To Reproduce
``` json
 "aoweiya": {
    "body": [
      "ava.com.cn"
    ]
  }
```
``` go
go run .\cmd\main.go -target 221.237.224.121
```

### Environment
Go: go1.23.2 windows/amd64
Zscan: v1.0.5

**Comment by YGHS4** [comment]
target: http://221.237.224.121:70/

**Comment by zcyberseclab** [comment]
fixed. 
Previously, ports less than 80 were treated as TCP ports by default without making HTTP requests, which caused errors with port 70. Now this has been changed to ports below 70.
