### ISSUE TITLE
[BUG] This site cannot provide a secure connection

### ISSUE THREAD

**Issue by YGHS4** [zcyberseclab/zscan#14]
### Current Behavior
Requested website This website can't provide a secure connection.

### Expected Behavior
The website has a vulnerability, which Zscan can detect.

### Steps To Reproduce
``` go
go run .\cmd\main.go -target 113.140.35.82
```

### Environment
Go: go1.23.2 windows/amd64
Zscan: v1.0.6

**Comment by YGHS4** [comment]
target: https://113.140.35.82:8443

**Comment by zcyberseclab** [comment]
works with command `go run .\cmd\main.go -target 113.140.35.82:8443`
