### ISSUE TITLE
[BUG] The scan results only show duplicate ports

### ISSUE THREAD

**Issue by YGHS4** [zcyberseclab/zscan#8]
### Current Behavior
![image](https://github.com/user-attachments/assets/04f2b1fb-b0ad-46ea-9fdd-bffa2c208357)

### Steps To Reproduce
``` go 
go run .\cmd\main.go -target malmaga.yonagoaruki.net
```
### Environment
``` bash
go version: go1.23.2 windows/amd64
zscan version: v1.0.4
```

**Comment by YGHS4** [comment]
target ip: http://221.237.224.121:70/

**Comment by zcyberseclab** [comment]
fixed.
not sure the root cause, after move to go version 1.22, this issue is gone
